PAD_WORD = "<PAD>"
UNKNOWN_WORD = "<UNK>"
START_WORD = "<BOS>"
END_WORD = "<EOS>"

PAD_INDEX = 0
UNKNOWN_INDEX = 1
START_INDEX = 2
END_INDEX = 3

KEEP_PROB_KEY = "keep_prob"
LABEL_KEY = "labels"
LENGTH_KEY = "lengths"
MARKER_KEY = "markers"
